
export interface TestimonialType {
    id: string,
    category: string,
    title: string,
    name: string,
    avatar: string,
    date: string,
    address: string,
    description: string,
    images: Array<string>,
    star: number,
}

export const testimonialsdata: TestimonialType[] = [
    {
        id: "1",
        category: "Product Review",
        title: "Excellent Quality!",
        name: "John Doe",
        avatar: "/avatars/john.jpg",
        date: "2024-02-10",
        address: "New York, USA",
        description: "The stainless steel cutlery exceeded my expectations! Highly recommended.",
        images: ["/images/review1.jpg", "/images/review2.jpg"],
        star: 5,
    },
    {
        id: "2",
        category: "Service Feedback",
        title: "Great Customer Support",
        name: "Jane Smith",
        avatar: "/avatars/jane.jpg",
        date: "2024-02-12",
        address: "London, UK",
        description: "The team was very helpful and resolved my issue quickly. Fantastic service!",
        images: ["/images/review3.jpg"],
        star: 4,
    },
    {
        id: "3",
        category: "Product Review",
        title: "Durable and Stylish",
        name: "Alex Johnson",
        avatar: "/avatars/alex.jpg",
        date: "2024-02-14",
        address: "Sydney, Australia",
        description: "Love the design and durability of the cookware. Worth every penny!",
        images: ["/images/review4.jpg", "/images/review5.jpg"],
        star: 5,
    },
    {
        id: "4",
        category: "General Feedback",
        title: "Fast Delivery",
        name: "Emily Davis",
        avatar: "/avatars/emily.jpg",
        date: "2024-02-16",
        address: "Toronto, Canada",
        description: "The order arrived earlier than expected. Super happy with the experience!",
        images: [],
        star: 4,
    }
];
